# Generated by Django 3.2.16 on 2022-10-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingentitymodel',
            name='entity_type',
            field=models.CharField(max_length=50),
        ),
    ]
